#IF 10
 #DEFINE DEBUG
 #DEFINE DEBUG_POINTER(_N_)
#ELSE
 COMMON SHARED AS ANY PTR DEBUG_ADDRESS, DEBUG_VALUE
 #DEFINE DEBUG _
  IF PEEK(ANY PTR, DEBUG_ADDRESS) <> DEBUG_VALUE THEN _
    ?"DEBUG error: ";__FILE__;":";__FUNCTION__;"(";__LINE__;!")\n  " _
     ;DEBUG_ADDRESS;" = ";PEEK(ANY PTR, DEBUG_ADDRESS)
 #DEFINE DEBUG_POINTER(_N_) _
   DEBUG_ADDRESS = @_N_ : DEBUG_VALUE = _N_ _
 : ?"DEBUG watching PEEK(ANY PTR, ";DEBUG_ADDRESS;") = ";DEBUG_VALUE
#ENDIF
